[package]
name = "scramble-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4"
dioxus-logger = "0.4"
dioxus-web = "0.4"
gloo-timers = "0.3"
log = "0.4"
reqwest = "0.11"
